### ISSUE TITLE
ia-download.py requires several manual restarts to download the full crawl

### ISSUE THREAD

**Issue by nvanva** [hplt-project/ia-download#2]
Currently ia-download.py goes through all input items only once. Download errors are reported, but you need restarting ia-download.py manually to make new attempt to download those files that were not downloaded during the previous attempt. Also after 100 consecutive errors the script stops, I have seen this 2 times already: one time for unclear reason (maybe, temporarily network problems), and another due to running out of free inodes(no space left on device error). It is reasonable to signal about consecutive errors, but probably continue trying to download will be better to avoid wasting time before we restart the script manually?
May I suggest the following modification. We create a queue and populate it with all the files (or items if we want to request urls lazily for some reason). Then download as before, but if a file fails to download we put it to the end of the queue with an integer indicating the number of attempts. This way we will try to download it again and again, but only after attempting to (re-)download other files. We stop only when the queue is empty, i.e. all files were successfully downloaded. Also we print the number of attempts to the log file, the user can see the number of attempts and interrupt the script manually if he wants to stop trying.
@jelmervdl  What do you think about this modification? It seems to me it will make ia-download.py more autonomous and easier to use for the future downloads. If you agree, I can try to implement this.

**Comment by jelmervdl** [comment]
I don't think they ever change.

This issue is "solved" with 4eb06d14159fa88ee6c2b8f68287d67a8561c5be.
